import React from "react";
import CICT_Logo from "../images/login/cict_logo.png";
import { useEffect, useState } from "react";
import axios from "axios";
import bulsu_icon from "../images/bulsu_icon.png";
import pdf_header from "../images/pdf_header.png";

export default function PendingUsersPDF(){
   
   //getting the email of user
   let email_key = localStorage.getItem("email");

   //Hook for getting all certificates
   const [getAllUser, setGetAllUser] = useState([]);
   const loadGetAllUser = async () => {
     const result = await axios.get("http://localhost/fms/getAllUser.php");
     setGetAllUser(result.data.phpresult);
   };
   useEffect(() => {
     loadGetAllUser();
   }, []);
 
   var input_keyForGetUser_ctr = 0;
   const input_keyForUser = getAllUser.map((res) => {
     if (res.email != email_key && res.account_status =="Pending") {
       input_keyForGetUser_ctr++;
       return (
        <div className="th1" key={input_keyForGetUser_ctr}>
          <div style={{width:"30%",fontWeight:"normal"}}>
            <span>{res.fname+" "+res.lname}</span>
          </div>
          <div style={{width:"35%",fontWeight:"normal"}}><span>{res.email}</span></div>
          <div style={{width:"35%",fontWeight:"normal"}}><span>{res.date_created}</span></div>
          </div>
       );
     }
   });
 

    return(
        <div className="certificatePDF_container">
            <div className="pdf_container" id="PendingUsers_pdf">

                <div className="top">
                  <img src={pdf_header}/>
                </div>


                <div className="th">
                    PENDING FACULTY ACCOUNTS
                </div>

                <div className="th1">
                    <div style={{width:"30%"}}><span>FACULTY</span></div>
                    <div style={{width:"35%"}}><span>EMAIL ADDRESS</span></div>
                    <div style={{width:"35%"}}><span>DATE AND TIME REGISTERED</span></div>
                </div>
                {input_keyForUser}
                <div className="bot_text_div">
                  <p className="bot_text"><b>Generated by : </b><span id="generatedPrint1"></span></p>
                  <p className="bot_text"><b>Date : </b><span id="datePrint1"></span></p>
                  <p className="bot_text"><b>Time : </b><span id="timePrint1"></span></p>
                </div>
            </div>


        </div>
    )
}

